'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import { Download, FileJson, FileText, Loader2 } from 'lucide-react';
import { useStore } from '@/lib/store';

interface ExportOptions {
    format: 'geojson' | 'pdf' | 'csv' | 'shapefile';
    includePhysics: boolean;
    includeAgentWeights: boolean;
    includeHistory: boolean;
}

export function ExportPanel() {
    const { selectedCity, simulationResult, agents, selectedParcels } = useStore();
    const [exporting, setExporting] = useState(false);
    const [options, setOptions] = useState<ExportOptions>({
        format: 'geojson',
        includePhysics: true,
        includeAgentWeights: true,
        includeHistory: false,
    });

    const handleExport = async () => {
        setExporting(true);

        try {
            if (options.format === 'geojson') {
                await exportGeoJSON();
            } else if (options.format === 'pdf') {
                await exportPDF();
            } else if (options.format === 'csv') {
                await exportCSV();
            }
        } catch (error) {
            console.error('Export failed:', error);
        } finally {
            setExporting(false);
        }
    };

    const exportGeoJSON = async () => {
        // Fetch parcel data and add simulation results
        const response = await fetch(`/api/cities/${selectedCity}/parcels`);
        const data = await response.json();

        // Add simulation metadata
        const exportData = {
            type: 'FeatureCollection',
            metadata: {
                city: selectedCity,
                exportedAt: new Date().toISOString(),
                agentWeights: options.includeAgentWeights
                    ? Object.fromEntries(agents.map((a) => [a.type, a.weight]))
                    : undefined,
                simulationResult: options.includePhysics ? simulationResult : undefined,
            },
            features: data.features.map((f: any) => ({
                ...f,
                properties: {
                    ...f.properties,
                    selected: selectedParcels.includes(f.properties.parcel_id),
                },
            })),
        };

        // Download
        const blob = new Blob([JSON.stringify(exportData, null, 2)], {
            type: 'application/geo+json',
        });
        downloadBlob(blob, `pimaluos_${selectedCity}_${Date.now()}.geojson`);
    };

    const exportPDF = async () => {
        // Create HTML report
        const reportHTML = `
<!DOCTYPE html>
<html>
<head>
  <title>PIMALUOS Report - ${selectedCity}</title>
  <style>
    body { font-family: system-ui, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
    h1 { color: #0ea5e9; }
    h2 { color: #6b7280; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px; }
    .metric { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #f3f4f6; }
    .metric-label { color: #6b7280; }
    .metric-value { font-weight: 600; }
    .agent { display: flex; align-items: center; gap: 12px; padding: 12px; background: #f9fafb; border-radius: 8px; margin-bottom: 8px; }
    .agent-color { width: 12px; height: 12px; border-radius: 50%; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { text-align: left; padding: 8px 12px; border: 1px solid #e5e7eb; }
    th { background: #f9fafb; }
  </style>
</head>
<body>
  <h1>PIMALUOS Simulation Report</h1>
  <p><strong>City:</strong> ${selectedCity}</p>
  <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
  
  <h2>Simulation Results</h2>
  ${simulationResult ? `
  <div class="metric">
    <span class="metric-label">Traffic Congestion</span>
    <span class="metric-value">${simulationResult.traffic.avgCongestion.toFixed(2)}</span>
  </div>
  <div class="metric">
    <span class="metric-label">Drainage Utilization</span>
    <span class="metric-value">${(simulationResult.hydrology.utilization * 100).toFixed(1)}%</span>
  </div>
  <div class="metric">
    <span class="metric-label">Solar Shadow</span>
    <span class="metric-value">${simulationResult.solar.shadowPct.toFixed(1)}%</span>
  </div>
  <div class="metric">
    <span class="metric-label">Total Violations</span>
    <span class="metric-value">${simulationResult.violations}</span>
  </div>
  ` : '<p>No simulation data available</p>'}
  
  <h2>Stakeholder Weights</h2>
  ${agents.map((a) => `
  <div class="agent">
    <div class="agent-color" style="background: ${a.color}"></div>
    <span style="flex: 1">${a.name}</span>
    <strong>${(a.weight * 100).toFixed(0)}%</strong>
  </div>
  `).join('')}
  
  <h2>Selected Parcels</h2>
  <p>${selectedParcels.length} parcels selected</p>
  
  <hr style="margin: 40px 0; border: none; border-top: 1px solid #e5e7eb;">
  <p style="color: #9ca3af; text-align: center; font-size: 12px;">
    Generated by PIMALUOS - Physics Informed Multi-Agent Land Use Optimization Software
  </p>
</body>
</html>
    `;

        // For actual PDF, you'd use a library like jsPDF or call a backend endpoint
        // Here we download as HTML which can be printed to PDF
        const blob = new Blob([reportHTML], { type: 'text/html' });
        downloadBlob(blob, `pimaluos_report_${selectedCity}_${Date.now()}.html`);
    };

    const exportCSV = async () => {
        const response = await fetch(`/api/cities/${selectedCity}/parcels`);
        const data = await response.json();

        // Convert to CSV
        const headers = ['parcel_id', 'address', 'zone', 'land_use', 'far', 'height_ft', 'selected'];
        const rows = data.features.map((f: any) => [
            f.properties.parcel_id,
            f.properties.address || '',
            f.properties.zone || '',
            f.properties.land_use || '',
            f.properties.far || '',
            f.properties.height_ft || '',
            selectedParcels.includes(f.properties.parcel_id) ? 'yes' : 'no',
        ]);

        const csv = [headers.join(','), ...rows.map((r: any[]) => r.join(','))].join('\n');
        const blob = new Blob([csv], { type: 'text/csv' });
        downloadBlob(blob, `pimaluos_${selectedCity}_${Date.now()}.csv`);
    };

    const downloadBlob = (blob: Blob, filename: string) => {
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    return (
        <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 z-50 glass w-96"
        >
            <div className="p-6">
                <h2 className="text-lg font-bold gradient-text mb-4">Export Data</h2>

                {/* Format Selection */}
                <div className="mb-4">
                    <label className="text-xs text-gray-400 mb-2 block">Export Format</label>
                    <div className="grid grid-cols-2 gap-2">
                        {[
                            { id: 'geojson', icon: FileJson, label: 'GeoJSON' },
                            { id: 'pdf', icon: FileText, label: 'PDF Report' },
                            { id: 'csv', icon: FileText, label: 'CSV' },
                        ].map(({ id, icon: Icon, label }) => (
                            <button
                                key={id}
                                onClick={() => setOptions({ ...options, format: id as ExportOptions['format'] })}
                                className={`
                  flex items-center gap-2 p-3 rounded-lg border transition
                  ${options.format === id
                                        ? 'bg-primary-500/20 border-primary-500 text-primary-400'
                                        : 'border-white/10 hover:bg-white/5'
                                    }
                `}
                            >
                                <Icon size={18} />
                                <span className="text-sm">{label}</span>
                            </button>
                        ))}
                    </div>
                </div>

                {/* Options */}
                <div className="space-y-2 mb-6">
                    <label className="flex items-center gap-2 text-sm">
                        <input
                            type="checkbox"
                            checked={options.includePhysics}
                            onChange={(e) => setOptions({ ...options, includePhysics: e.target.checked })}
                            className="rounded"
                        />
                        Include physics simulation results
                    </label>
                    <label className="flex items-center gap-2 text-sm">
                        <input
                            type="checkbox"
                            checked={options.includeAgentWeights}
                            onChange={(e) => setOptions({ ...options, includeAgentWeights: e.target.checked })}
                            className="rounded"
                        />
                        Include agent weights
                    </label>
                </div>

                {/* Export Button */}
                <button
                    onClick={handleExport}
                    disabled={exporting}
                    className="w-full py-3 bg-gradient-to-r from-primary-500 to-accent-500 rounded-lg font-medium flex items-center justify-center gap-2 disabled:opacity-50"
                >
                    {exporting ? (
                        <>
                            <Loader2 size={18} className="animate-spin" />
                            Exporting...
                        </>
                    ) : (
                        <>
                            <Download size={18} />
                            Export {options.format.toUpperCase()}
                        </>
                    )}
                </button>
            </div>
        </motion.div>
    );
}

export default ExportPanel;
