"""
Turn a results directory into manuscript assets.

    pimaluos report --results results/paper --out paper/generated [--rag results/rag]

Writes ``macros.tex`` (every number quoted in the text), ``tab_*.tex`` and
``fig_*.pdf``. Every macro in :data:`MACROS` is always defined; values that are
unavailable render as ``\\textbf{[TBD]}`` so a missing experiment is visible in
the PDF instead of silently omitted. ``write_pending`` writes the all-TBD file
used before any run exists.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Dict, Optional

import numpy as np
import pandas as pd

TBD = r"\textbf{[TBD]}"

MACROS = [
    # data / graph
    "NParcels", "NParcelsRaw", "NFeaturesEngineered", "NFeatures", "PlutoRelease",
    "NEdgesDirected", "NEdgesUndirected", "NIsolated",
    "EdgesAdjDir", "EdgesProxDir", "EdgesFunDir", "EdgesStreetDir", "EdgesRegDir",
    "ExistingFAM", "ZoningCapFAM", "LotsHeadroom", "LotsAboveMax", "NTaz", "NCatch", "ExistingTazOverRaw",
    "NVulnerable", "NFlood", "ExistingTazOver", "NSeeds", "NSeedsAbl", "NSeedsPareto",
    # GNN
    "GnnValLoss", "GnnMeanPredLoss", "GnnNoGraphLoss", "GnnEpochs", "GnnBestEpoch",
    # main results (verified PIMALUOS vs comparators)
    "PimAddedFAM", "PimAddedFAVerM", "PimTrafficViol", "PimSewerViol", "PimShaded",
    "PimShadedVer", "PimDispShare", "PimRepairIters",
    "BuildoutAddedFAM", "BuildoutVerAddedFAM", "BuildoutTrafficViol", "BuildoutSewerViol", "BuildoutShaded",
    "NoGnnAddedFAVerM", "NoCapAddedFAM", "NoCapShaded", "SingleAddedFAVerM", "NoEquityDispShare",
    "PimVsBuildoutVerPct", "PimVsNoGnnVerPct",
    # Nash
    "NashLots", "NashNontrivial", "NashShareSincereOpt", "NashLossSincere", "NashLossWorstNE",
    "NashMedianPoA", "NashPoaDefined", "NashMeanNE",
    # Pareto
    "ParetoPop", "ParetoGen", "ParetoRefDirs", "ParetoNCold", "ParetoNSeeded", "HVCold", "HVSeeded",
    "KneeSeededAddedFAM", "KneeSeededShaded", "ParetoColdInBox", "ParetoDomPim", "ParetoDomPimVer",
    "ParetoDomBuildoutVer",
    # budgets
    "GnnPatience", "MarlIters", "MarlHorizon", "AblEpochs",
    # timings / hardware
    "TimeTotalH", "GnnSecPerEpoch", "MarlSecPerIter", "AblMinPerConfig", "ParetoMinPerRun", "TimeGraphS",
    "Hardware", "TorchVersion",
    # RAG
    "RagProvider", "RagDistricts", "RagAccOverall", "RagAccCI", "RagAccResid", "RagAccComm", "RagAccFacil",
    "RagCoverage", "RagParseFail", "RagRefAgreement", "RagChunks",
]


def _fmt(x, nd=2):
    if x is None or (isinstance(x, float) and not math.isfinite(x)):
        return TBD
    if isinstance(x, (int, np.integer)):
        return f"{int(x):,}".replace(",", "{,}")
    return f"{x:,.{nd}f}".replace(",", "{,}")


def _rate(t: Dict, seconds: str, count: Optional[str], n: Optional[int] = None) -> float:
    n = t.get(count, 0) if count else n
    return t[seconds] / n if n and t.get(seconds) else np.nan


def _n_abl_runs(abl) -> int:
    return sum(len(v.get("val_loss", {})) for k, v in (abl or {}).items() if k != "mean_predictor")


def _n_pareto_runs(pareto) -> int:
    return sum(len(v) for v in (pareto or {}).values())


def _compute_hours(t: Dict, config: Dict, gnn: Optional[Dict] = None) -> float:
    """Total computation in hours. Stages interrupted and resumed count only the work
    done after resuming, so GNN pre-training and multi-agent training are the measured
    seconds per epoch/iteration times the epochs/iterations the run required."""
    epochs = (sum(len(h["train_loss"]) for h in gnn.values()) if gnn
              else len(config["seeds"]) * config["gnn"]["epochs"])
    gnn_s = _rate(t, "gnn_s", "gnn_epochs") * epochs
    marl_s = _rate(t, "marl_s", "marl_iters") * len(config["seeds"]) * len(config["variants"]) \
        * config["marl"]["iterations"]
    keys = ("data_s", "graph_s", "edge_ablation_s", "pareto_s")
    if not (np.isfinite(gnn_s) and np.isfinite(marl_s)) or any(k not in t for k in keys):
        return t.get("total_s", np.nan) / 3600
    return (sum(t[k] for k in keys) + gnn_s + marl_s) / 3600


def _hardware_text(env: Dict) -> str:
    if env.get("cpu_count"):
        txt = f"{env['cpu_count']} CPU cores ({env['cpu_model']})"
        if env.get("memory_gb"):
            txt += f" with {env['memory_gb']:g} GB memory"
        txt += ", using the GPU" if env.get("cuda") else ", no GPU"
    else:
        txt = env.get("processor") or env["platform"]
    return txt.replace("_", r"\_").replace("(R)", "").replace("@", "at")


def _pm(vals, nd=2, scale=1.0):
    v = np.asarray([x for x in vals if x is not None and np.isfinite(x)], dtype=float) * scale
    if len(v) == 0:
        return TBD
    if len(v) == 1:
        return _fmt(float(v[0]), nd)
    return f"{_fmt(float(v.mean()), nd)} $\\pm$ {_fmt(float(v.std(ddof=1)), nd)}"


def write_macros(values: Dict[str, str], path: Path):
    lines = ["% Auto-generated by pimaluos.reporting -- do not edit by hand."]
    for name in MACROS:
        lines.append(f"\\providecommand{{\\{name}}}{{}}\\renewcommand{{\\{name}}}{{{values.get(name, TBD)}}}")
    path.write_text("\n".join(lines) + "\n")


TABLE_COLUMNS = {"tab_graph_rows": 3, "tab_edge_ablation_rows": 3, "tab_main_rows": 8,
                 "tab_voting_rows": 4, "tab_rag_rows": 4}


def _fill_missing(out: Path):
    """Every table/list file the manuscript inputs must exist; missing ones get a TBD row."""
    for name, ncol in TABLE_COLUMNS.items():
        f = out / f"{name}.tex"
        if not f.exists():
            f.write_text(f"\\multicolumn{{{ncol}}}{{c}}{{{TBD} (run \\texttt{{pimaluos report}})}} \\\\\n")
    f = out / "features_used.tex"
    if not f.exists():
        f.write_text(TBD + "\n")


def write_pending(out: Path):
    """Write the all-TBD asset folder used before any run exists (paper/pending)."""
    out.mkdir(parents=True, exist_ok=True)
    write_macros({}, out / "macros.tex")
    _fill_missing(out)


def _metric(df: pd.DataFrame, method: str, metric: str, verified: bool):
    s = df[(df.method == method) & (df.metric == metric) & (df.verified == verified)]
    return s.sort_values("seed")["value"].astype(float).tolist()


# --------------------------------------------------------------------- figures
SERIES = ["#2a78d6", "#eb6834", "#1baf7a"]  # categorical slots 1-3 (fixed order)
GREY, INK, MUTED, GRID = "#8a8986", "#0b0b0b", "#52514e", "#e4e3df"


def _style():
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    plt.rcParams.update({
        "font.family": "DejaVu Sans", "font.size": 8, "axes.titlesize": 9, "axes.labelsize": 8,
        "axes.edgecolor": MUTED, "axes.labelcolor": INK, "xtick.color": MUTED, "ytick.color": MUTED,
        "axes.grid": True, "grid.color": GRID, "grid.linewidth": 0.5, "axes.spines.top": False,
        "axes.spines.right": False, "lines.linewidth": 1.5, "legend.frameon": False,
        "savefig.bbox": "tight", "savefig.dpi": 300,
    })
    return plt


def _band(ax, curves, color, label):
    L = min(len(c) for c in curves)
    a = np.array([c[:L] for c in curves])
    m, s = a.mean(0), a.std(0)
    x = np.arange(1, L + 1)
    ax.plot(x, m, color=color, label=label)
    if len(curves) > 1:
        ax.fill_between(x, m - s, m + s, color=color, alpha=0.18, linewidth=0)


def fig_gnn(gnn: Dict, out: Path):
    plt = _style()
    fig, ax = plt.subplots(figsize=(3.4, 2.4))
    _band(ax, [h["train_loss"] for h in gnn.values()], SERIES[0], "Training (masked train nodes)")
    _band(ax, [h["val_loss"] for h in gnn.values()], SERIES[1], "Validation (masked held-out nodes)")
    ref = np.mean([h["mean_predictor_val_loss"] for h in gnn.values()])
    ax.axhline(ref, color=GREY, linestyle="--", linewidth=1)
    ax.text(1, ref, " feature-mean predictor", va="bottom", color=MUTED, fontsize=7)
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Masked reconstruction MSE")
    ax.legend(loc="upper right", fontsize=7)
    fig.savefig(out / "fig_gnn_loss.pdf")
    plt.close(fig)


def fig_marl(marl: Dict, out: Path):
    plt = _style()
    agents = ["resident", "developer", "planner", "environmentalist", "equity_advocate"]
    fig, axes = plt.subplots(1, 5, figsize=(7.0, 1.7), sharex=True)
    for ax, a in zip(axes, agents):
        curves = [[h["returns"][a] for h in marl[s]["pimaluos"]] for s in marl if "pimaluos" in marl[s]]
        if curves:
            _band(ax, curves, SERIES[0], a)
        ax.set_title(a.replace("_", " "), fontsize=8)
        ax.set_xlabel("Iteration")
    axes[0].set_ylabel("Episode return")
    fig.tight_layout()
    fig.savefig(out / "fig_marl_returns.pdf")
    plt.close(fig)


def fig_tradeoff(df: pd.DataFrame, pareto: Optional[Dict], out: Path):
    """Added floor area vs newly shaded lots, all *before* verification (the space NSGA-III searches)."""
    plt = _style()
    fig, ax = plt.subplots(figsize=(3.6, 2.8))
    if pareto:
        s0 = sorted(pareto, key=lambda k: int(k))[0]
        for mode, c in [("cold", SERIES[2]), ("seeded", SERIES[1])]:
            F = np.array(pareto[s0][mode]["F"])
            ax.scatter(-F[:, 0] / 1e6, F[:, 2], s=9, color=c, alpha=0.6, linewidths=0,
                       label=f"NSGA-III front ({mode} start)")
    labelled = {"zoning_buildout": "Build-out", "rule_based": "Rule-based", "random": "Random",
                "pimaluos": "PIMALUOS"}
    ablations = ["no_gnn", "no_capacity_feedback", "single_agent_planner", "no_equity_agent"]

    def point(m):
        fa = _metric(df, m, "added_floor_area_sqft", False)
        sh = _metric(df, m, "lots_newly_shaded", False)
        return (np.mean(fa) / 1e6, np.mean(sh)) if fa else None

    first = True
    for m in ablations:
        p = point(m)
        if p:
            ax.scatter(*p, s=22, facecolors="none", edgecolors=GREY, linewidths=1.0, zorder=3,
                       label="PIMALUOS ablations (Table)" if first else None)
            first = False
    for m, lab in labelled.items():
        p = point(m)
        if not p:
            continue
        col = SERIES[0] if m == "pimaluos" else GREY
        ax.scatter(*p, s=28, color=col, edgecolors="white", linewidths=0.8, zorder=4)
        ax.annotate(lab, p, fontsize=6.5, color=INK, xytext=(4, -9 if m == "pimaluos" else 3),
                    textcoords="offset points")
    ax.set_xlabel("Added floor area (million sq ft)")
    ax.set_ylabel("Lots newly shaded")
    ax.legend(loc="upper left", fontsize=6.5)
    fig.savefig(out / "fig_tradeoff.pdf")
    plt.close(fig)


def fig_hv(pareto: Dict, out: Path):
    plt = _style()
    fig, ax = plt.subplots(figsize=(3.4, 2.3))
    for mode, c in [("cold", SERIES[2]), ("seeded", SERIES[1])]:
        _band(ax, [pareto[s][mode]["hv"] for s in pareto], c, mode.capitalize() + " start")
    ax.set_xlabel("Generation")
    ax.set_ylabel("Normalised hypervolume")
    ax.legend(fontsize=7)
    fig.savefig(out / "fig_hypervolume.pdf")
    plt.close(fig)


def fig_map(results: Path, out: Path):
    lots, plan = results / "plans" / "lots.npz", results / "plans" / "pimaluos.npz"
    geom = results / "plans" / "lots_geometry.parquet"
    if not (lots.exists() and plan.exists() and geom.exists()):
        return
    import geopandas as gpd

    plt = _style()
    L, P = np.load(lots), np.load(plan)
    g = gpd.read_parquet(geom)
    g["dfar"] = P["far_verified"] - L["far0"]
    fig, ax = plt.subplots(figsize=(3.2, 5.4))
    g.plot(ax=ax, color=GRID, linewidth=0)
    inc = g[g["dfar"] > 1e-9]
    if len(inc):
        vmax = float(np.quantile(inc["dfar"], 0.98)) or 1.0
        inc.plot(ax=ax, column="dfar", cmap="Blues", vmin=0, vmax=vmax, linewidth=0, legend=True,
                 legend_kwds={"label": "FAR increase", "shrink": 0.4})
    ax.set_aspect("equal")
    ax.axis("off")
    fig.savefig(out / "fig_map.pdf")
    plt.close(fig)


# --------------------------------------------------------------------- tables
METHOD_ROWS = [("status_quo", "Status quo"), ("random", "Random"), ("rule_based", "Rule-based"),
               ("zoning_buildout", "Zoning build-out"), ("pimaluos", "PIMALUOS"),
               ("no_gnn", "\\quad No GNN"), ("no_capacity_feedback", "\\quad No capacity feedback"),
               ("single_agent_planner", "\\quad Single agent (planner)"),
               ("no_equity_agent", "\\quad No equity agent")]


def table_main(df: pd.DataFrame, out: Path):
    cols = [("added_floor_area_sqft", False, 1e-6, 2), ("traffic_violations", False, 1, 1),
            ("catchments_over_capacity", False, 1, 1), ("lots_newly_shaded", False, 1, 0),
            ("displacement_exposure_share", False, 100, 1), ("added_floor_area_sqft", True, 1e-6, 2),
            ("repair_iterations", True, 1, 1)]
    lines = []
    for m, lab in METHOD_ROWS:
        if not _metric(df, m, "added_floor_area_sqft", False):
            continue
        cells = [_pm(_metric(df, m, k, v), nd, sc) for k, v, sc, nd in cols]
        lines.append(lab + " & " + " & ".join(cells) + r" \\")
    (out / "tab_main_rows.tex").write_text("\n".join(lines) + "\n")


def table_graph(graph: Dict, out: Path):
    names = {"spatial_adjacency": "Spatial adjacency", "proximity": "Proximity (k-NN)",
             "functional_similarity": "Functional similarity", "street_frontage": "Street frontage",
             "regulatory_coupling": "Regulatory coupling"}
    lines = []
    for k, lab in names.items():
        e = graph["edge_types"].get(k)
        if e:
            lines.append(f"{lab} & {_fmt(e['directed'])} & {_fmt(e['undirected'])} \\\\")
    lines.append(r"\midrule")
    lines.append(f"Total & {_fmt(graph['total_directed'])} & {_fmt(graph['total_undirected'])} \\\\")
    (out / "tab_graph_rows.tex").write_text("\n".join(lines) + "\n")


def table_ablation(abl: Dict, out: Path):
    order = ["all"] + [k for k in abl if k.startswith("without_")] + ["spatial_adjacency_only", "no_graph",
                                                                     "mean_predictor"]
    lab = {"all": "All five relations", "spatial_adjacency_only": "Spatial adjacency only",
           "no_graph": "No graph (MLP)", "mean_predictor": "Feature-mean predictor"}
    lines = []
    for k in order:
        if k not in abl:
            continue
        name = lab.get(k, "Without " + k.replace("without_", "").replace("_", " "))
        lines.append(f"{name} & {len(abl[k]['edge_types'])} & {_pm(list(abl[k]['val_loss'].values()), 3)} \\\\")
    (out / "tab_edge_ablation_rows.tex").write_text("\n".join(lines) + "\n")


def table_voting(vote: Dict, out: Path):
    if not vote:
        return
    ws = [r["developer_weight"] for r in next(iter(vote.values()))]
    lines = []
    for i, w in enumerate(ws):
        fa = [vote[s][i]["added_floor_area_sqft"] for s in vote]
        sh = [vote[s][i]["lots_newly_shaded"] for s in vote]
        tv = [vote[s][i]["traffic_violations"] for s in vote]
        lines.append(f"{w:.2f} & {_pm(fa, 2, 1e-6)} & {_pm(tv, 1)} & {_pm(sh, 0)} \\\\")
    (out / "tab_voting_rows.tex").write_text("\n".join(lines) + "\n")


def table_rag(rag: Dict, out: Path):
    names = {"max_residential_far": "Residential FAR", "max_commercial_far": "Commercial FAR",
             "max_community_facility_far": "Community facility FAR"}
    lines = []
    for k, lab in names.items():
        r = rag[k]
        lo, hi = r["accuracy_ci95"]
        lines.append(f"{lab} & {_fmt(100 * r['coverage'], 1)} & {_fmt(100 * r['accuracy'], 1)} "
                     f"[{_fmt(100 * lo, 1)}, {_fmt(100 * hi, 1)}] & {_fmt(r['mae_answered'], 2)} \\\\")
    (out / "tab_rag_rows.tex").write_text("\n".join(lines) + "\n")


def table_features(manifest: Dict, out: Path):
    feats = manifest["data"]["features_used"]
    txt = ", \\allowbreak ".join("\\texttt{" + f.replace("_", r"\_") + "}" for f in feats)
    (out / "features_used.tex").write_text(txt + "\n")


# --------------------------------------------------------------------- main
def make_report(results: Path, out: Path, rag_dir: Optional[Path] = None) -> Dict[str, str]:
    out.mkdir(parents=True, exist_ok=True)
    R = lambda name: json.loads((results / name).read_text()) if (results / name).exists() else None  # noqa: E731
    man, graph = R("manifest.json"), R("graph_summary.json")
    gnn, abl, marl = R("gnn.json"), R("edge_ablation.json"), R("marl.json")
    nash, vote, pareto = R("nash.json"), R("voting_sensitivity.json"), R("pareto.json")
    df = pd.read_csv(results / "metrics.csv") if (results / "metrics.csv").exists() else pd.DataFrame(
        columns=["seed", "method", "verified", "metric", "value"])
    v: Dict[str, str] = {}

    if man:
        d, ds, t = man["data"], man["data_stats"], man["timings"]
        if d.get("synthetic"):
            print("WARNING: results come from the SYNTHETIC test city; do not report them.")
        v.update(NParcels=_fmt(d["n_parcels_used"]), NParcelsRaw=_fmt(d["n_parcels_in_study_area"]),
                 NFeaturesEngineered=_fmt(d["n_features_engineered"]), NFeatures=_fmt(d["n_features_used"]),
                 PlutoRelease=(", ".join(d.get("pluto_versions") or [])
                               or str(man["config"].get("pluto_release") or TBD)),
                 ExistingFAM=_fmt(ds["existing_floor_area_sqft"] / 1e6, 1),
                 ZoningCapFAM=_fmt(ds["zoning_capacity_floor_area_sqft"] / 1e6, 1),
                 LotsHeadroom=_fmt(ds["lots_with_headroom"]), LotsAboveMax=_fmt(ds["lots_above_zoning_max_existing"]),
                 NTaz=_fmt(ds["n_taz"]), NCatch=_fmt(ds["n_catchments"]), NVulnerable=_fmt(ds["n_vulnerable_lots"]),
                 NFlood=_fmt(ds["n_flood_lots"]), ExistingTazOver=_fmt(ds["existing_taz_over_capacity"]),
                 ExistingTazOverRaw=_fmt(ds.get("existing_taz_over_capacity_frontage_only")),
                 NSeeds=_fmt(len(man["config"]["seeds"])),
                 NSeedsAbl=_fmt(len(man["config"]["edge_ablation"]["seeds"])),
                 NSeedsPareto=_fmt(len(man["config"]["pareto"]["seeds"])),
                 GnnEpochs=_fmt(man["config"]["gnn"]["epochs"]),
                 GnnPatience=_fmt(man["config"]["gnn"].get("patience", 50)),
                 MarlIters=_fmt(man["config"]["marl"]["iterations"]),
                 MarlHorizon=_fmt(man["config"]["marl"]["horizon"]),
                 AblEpochs=_fmt(man["config"]["edge_ablation"].get("epochs")),
                 ParetoPop=_fmt(man["config"]["pareto"]["pop_size"]),
                 ParetoGen=_fmt(man["config"]["pareto"]["generations"]),
                 TimeTotalH=_fmt(_compute_hours(t, man["config"], gnn), 1),
                 GnnSecPerEpoch=_fmt(_rate(t, "gnn_s", "gnn_epochs"), 1),
                 MarlSecPerIter=_fmt(_rate(t, "marl_s", "marl_iters"), 1),
                 AblMinPerConfig=_fmt(_rate(t, "edge_ablation_s", None, n=_n_abl_runs(abl)) / 60, 1),
                 ParetoMinPerRun=_fmt(_rate(t, "pareto_s", None, n=_n_pareto_runs(pareto)) / 60, 1),
                 TimeGraphS=_fmt(t.get("graph_s", np.nan), 0),
                 Hardware=_hardware_text(man["environment"]),
                 TorchVersion=man["environment"]["torch"].replace("_", r"\_"))
        table_features(man, out)
    if graph:
        e = graph["edge_types"]
        v.update(NEdgesDirected=_fmt(graph["total_directed"]), NEdgesUndirected=_fmt(graph["total_undirected"]),
                 NIsolated=_fmt(graph["isolated_nodes"]),
                 EdgesAdjDir=_fmt(e.get("spatial_adjacency", {}).get("directed")),
                 EdgesProxDir=_fmt(e.get("proximity", {}).get("directed")),
                 EdgesFunDir=_fmt(e.get("functional_similarity", {}).get("directed")),
                 EdgesStreetDir=_fmt(e.get("street_frontage", {}).get("directed")),
                 EdgesRegDir=_fmt(e.get("regulatory_coupling", {}).get("directed")))
        table_graph(graph, out)
    if gnn:
        v.update(GnnValLoss=_pm([h["best_val_loss"] for h in gnn.values()], 3),
                 GnnMeanPredLoss=_pm([h["mean_predictor_val_loss"] for h in gnn.values()], 3),
                 GnnBestEpoch=_pm([h["best_epoch"] for h in gnn.values()], 0))
        fig_gnn(gnn, out)
    if abl:
        v["GnnNoGraphLoss"] = _pm(list(abl["no_graph"]["val_loss"].values()), 3)
        table_ablation(abl, out)
    if len(df):
        mm = lambda m, k, ver, sc=1.0, nd=2: _pm(_metric(df, m, k, ver), nd, sc)  # noqa: E731
        v.update(PimAddedFAM=mm("pimaluos", "added_floor_area_sqft", False, 1e-6),
                 PimAddedFAVerM=mm("pimaluos", "added_floor_area_sqft", True, 1e-6),
                 PimTrafficViol=mm("pimaluos", "traffic_violations", False, 1, 1),
                 PimSewerViol=mm("pimaluos", "catchments_over_capacity", False, 1, 1),
                 PimShaded=mm("pimaluos", "lots_newly_shaded", False, 1, 0),
                 PimShadedVer=mm("pimaluos", "lots_newly_shaded", True, 1, 0),
                 PimDispShare=mm("pimaluos", "displacement_exposure_share", False, 100, 1),
                 PimRepairIters=mm("pimaluos", "repair_iterations", True, 1, 1),
                 BuildoutAddedFAM=mm("zoning_buildout", "added_floor_area_sqft", False, 1e-6),
                 BuildoutVerAddedFAM=mm("zoning_buildout", "added_floor_area_sqft", True, 1e-6),
                 BuildoutTrafficViol=mm("zoning_buildout", "traffic_violations", False, 1, 0),
                 BuildoutSewerViol=mm("zoning_buildout", "catchments_over_capacity", False, 1, 0),
                 BuildoutShaded=mm("zoning_buildout", "lots_newly_shaded", False, 1, 0),
                 NoGnnAddedFAVerM=mm("no_gnn", "added_floor_area_sqft", True, 1e-6),
                 NoCapAddedFAM=mm("no_capacity_feedback", "added_floor_area_sqft", False, 1e-6),
                 NoCapShaded=mm("no_capacity_feedback", "lots_newly_shaded", False, 1, 0),
                 SingleAddedFAVerM=mm("single_agent_planner", "added_floor_area_sqft", True, 1e-6),
                 NoEquityDispShare=mm("no_equity_agent", "displacement_exposure_share", False, 100, 1))

        def pct(a, b):
            x, y = np.array(_metric(df, a, "added_floor_area_sqft", True)), np.array(
                _metric(df, b, "added_floor_area_sqft", True))
            if len(x) == 0 or len(x) != len(y) or np.any(y == 0):
                return TBD
            return _pm(list(100 * (x - y) / y), 1)

        v["PimVsBuildoutVerPct"] = pct("pimaluos", "zoning_buildout")
        v["PimVsNoGnnVerPct"] = pct("pimaluos", "no_gnn")
        table_main(df, out)
        fig_tradeoff(df, pareto, out)
    if marl:
        fig_marl(marl, out)
    if nash:
        S = [nash[s]["summary"] for s in nash]
        v.update(NashLots=_fmt(S[0]["n_lots"]), NashNontrivial=_pm([s["n_nontrivial"] for s in S], 0),
                 NashShareSincereOpt=_pm([100 * s["share_sincere_optimal"] for s in S], 1),
                 NashLossSincere=_pm([s["mean_welfare_loss_sincere"] for s in S], 3),
                 NashLossWorstNE=_pm([s["mean_welfare_loss_worst_ne"] for s in S], 3),
                 NashMedianPoA=_pm([s["median_poa"] for s in S], 2),
                 NashPoaDefined=_pm([100 * s["share_poa_defined"] for s in S], 1),
                 NashMeanNE=_pm([s["mean_ne_outcomes"] for s in S], 2))
    if vote:
        table_voting(vote, out)
    if pareto:
        P = list(pareto.values())
        v.update(ParetoRefDirs=_fmt(P[0]["cold"]["n_ref_dirs"]),
                 ParetoNCold=_pm([p["cold"]["n_solutions"] for p in P], 0),
                 ParetoNSeeded=_pm([p["seeded"]["n_solutions"] for p in P], 0),
                 HVCold=_pm([p["cold"]["hv"][-1] for p in P], 3), HVSeeded=_pm([p["seeded"]["hv"][-1] for p in P], 3),
                 KneeSeededAddedFAM=_pm([p["seeded"]["knee_summary"]["added_floor_area_sqft"] for p in P], 2, 1e-6),
                 KneeSeededShaded=_pm([p["seeded"]["knee_summary"]["lots_newly_shaded"] for p in P], 0),
                 ParetoColdInBox=_fmt(int(sum(p["cold"].get("n_in_reference_box", 0) for p in P)))
                 if all("n_in_reference_box" in p["cold"] for p in P) else TBD)
        for key, plan in [("ParetoDomPim", "pimaluos"), ("ParetoDomPimVer", "pimaluos_verified"),
                          ("ParetoDomBuildoutVer", "zoning_buildout_verified")]:
            d = [p["seeded"].get("dominates_plan", {}).get(plan) for p in P]
            v[key] = f"{sum(map(bool, d))} of {len(d)}" if all(x is not None for x in d) else TBD
        fig_hv(pareto, out)
    fig_map(results, out)

    if rag_dir and (rag_dir / "rag_results.json").exists():
        rag = json.loads((rag_dir / "rag_results.json").read_text())
        lo, hi = rag["overall_accuracy_ci95"]
        v.update(RagProvider=rag["provider"].replace("_", r"\_"), RagDistricts=_fmt(rag["n_districts"]),
                 RagAccOverall=_fmt(100 * rag["overall_accuracy"], 1),
                 RagAccCI=f"{_fmt(100 * lo, 1)}--{_fmt(100 * hi, 1)}",
                 RagAccResid=_fmt(100 * rag["max_residential_far"]["accuracy"], 1),
                 RagAccComm=_fmt(100 * rag["max_commercial_far"]["accuracy"], 1),
                 RagAccFacil=_fmt(100 * rag["max_community_facility_far"]["accuracy"], 1),
                 RagCoverage=_fmt(100 * np.mean([rag[f]["coverage"] for f in
                                                 ["max_residential_far", "max_commercial_far",
                                                  "max_community_facility_far"]]), 1),
                 RagParseFail=_fmt(rag["parse_failures"]), RagChunks=_fmt(rag["n_chunks"]),
                 RagRefAgreement=_fmt(100 * np.mean(list(rag["reference_mean_agreement"].values())), 1))
        table_rag(rag, out)

    write_macros(v, out / "macros.tex")
    _fill_missing(out)
    return v
